services:
  nginx:
    image: nginx:1.26.3
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/
    environment:
      - APP_ENV=production

  scheduler:
    image: php:8.2-cli
    volumes:
      - .:/var/www/html
    entrypoint: >
      sh -c "while true; do php /var/www/html/artisan schedule:run; sleep 60; done"